src/Entity/Book.php
<?php

namespace App\Entity;

use App\Repository\BookRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\DBAL\Types\Types;
use App\Enum\BookStatus;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BookRepository::class)]
class Book
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[Assert\NotBlank()]
    #[ORM\Column(length: 255)]
    private ?string $Title = null;

    #[Assert\Isbn(type: 'isbn13')]
    #[Assert\NotBlank()]
    #[Assert\Length(min: 13, max: 13)]
    #[ORM\Column(length: 255)]
    private ?string $ISBN = null;

    #[Assert\NotBlank()]
    #[Assert\Url()]
    #[ORM\Column(length: 255)]
    private ?string $Cover = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $EditedAt = null;

    #[Assert\NotBlank()]
    #[Assert\Length(min: 20)]
    #[ORM\Column(type: Types::TEXT)]
    private ?string $Plot = null;

    #[Assert\NotBlank()]
    #[Assert\Type(type: 'integer')]
    #[Assert\Length(max: 4)]
    #[ORM\Column]
    private ?int $PageNumber = null;

    #[ORM\Column(length: 255)]
    private ?BookStatus $Status = null;

    #[ORM\ManyToOne(inversedBy: 'books')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Editor $editor = null;

    /**
     * @var Collection<int, Author>
     */
    #[ORM\ManyToMany(targetEntity: Author::class, mappedBy: 'books')]
    private Collection $authors;

    /**
     * @var Collection<int, Comment>
     */
    #[ORM\OneToMany(targetEntity: Comment::class, mappedBy: 'book', orphanRemoval: true)]
    private Collection $comments;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $createdBy = null;

    public function __construct()
    {
        $this->authors = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->Title;
    }

    public function setTitle(string $Title): static
    {
        $this->Title = $Title;

        return $this;
    }

    public function getISBN(): ?string
    {
        return $this->ISBN;
    }

    public function setISBN(string $ISBN): static
    {
        $this->ISBN = $ISBN;

        return $this;
    }

    public function getCover(): ?string
    {
        return $this->Cover;
    }

    public function setCover(string $Cover): static
    {
        $this->Cover = $Cover;

        return $this;
    }

    public function getEditedAt(): ?\DateTimeImmutable
    {
        return $this->EditedAt;
    }

    public function setEditedAt(\DateTimeImmutable $EditedAt): static
    {
        $this->EditedAt = $EditedAt;

        return $this;
    }

    public function getPlot(): ?string
    {
        return $this->Plot;
    }

    public function setPlot(string $Plot): static
    {
        $this->Plot = $Plot;

        return $this;
    }

    public function getPageNumber(): ?int
    {
        return $this->PageNumber;
    }

    public function setPageNumber(int $PageNumber): static
    {
        $this->PageNumber = $PageNumber;

        return $this;
    }

    public function getStatus(): ?BookStatus
    {
        return $this->Status;
    }

    public function setStatus(BookStatus $Status): static
    {
        $this->Status = $Status;

        return $this;
    }

    public function getEditor(): ?Editor
    {
        return $this->editor;
    }

    public function setEditor(?Editor $editor): static
    {
        $this->editor = $editor;

        return $this;
    }

    /**
     * @return Collection<int, Author>
     */
    public function getAuthors(): Collection
    {
        return $this->authors;
    }

    public function addAuthor(Author $author): static
    {
        if (!$this->authors->contains($author)) {
            $this->authors->add($author);
            $author->addBook($this);
        }

        return $this;
    }

    public function removeAuthor(Author $author): static
    {
        if ($this->authors->removeElement($author)) {
            $author->removeBook($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): static
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setBook($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): static
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getBook() === $this) {
                $comment->setBook(null);
            }
        }

        return $this;
    }

    public function getCreatedBy(): ?User
    {
        return $this->createdBy;
    }

    public function setCreatedBy(?User $createdBy): static
    {
        $this->createdBy = $createdBy;

        return $this;
    }
}

src/Form/BookType.php
<?php

namespace App\Form;

use App\Entity\Author;
use App\Entity\Book;
use App\Entity\Editor;
use App\Enum\BookStatus;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\EnumType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\UrlType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class BookType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Title', TextType::class, [
                'label' => 'Nom',
            ])
            ->add('ISBN', TextType::class, [
                'label' => 'Code du livre',
            ])
            ->add('Cover', UrlType::class, [
                'label' => 'URL de la couverture',
            ])
            ->add('EditedAt', DateType::class, [
                'label' => 'Date d\'édition',
                'widget' => 'single_text',
                'input' => 'datetime_immutable',
            ])
            ->add('Plot', TextareaType::class, [
                'label' => 'résumé',

            ])
            ->add('PageNumber', NumberType::class, [
                'label' => 'Nombre de pages',
            ])
            ->add('status', EnumType::class, [
                'class' => BookStatus::class,
            ])

            ->add('editor', EntityType::class, [
                'label' => 'Editeurs',
                'class' => Editor::class,
                'choice_label' => 'name',
            ])
            ->add('authors', EntityType::class, [
                'label' => 'Les auteurs',
                'class' => Author::class,
                'choice_label' => 'name',
                'multiple' => true,
                'by_reference' => false,
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Book::class,
        ]);
    }
}

src/Controller/Admin/BookController.php
<?php

namespace App\Controller\Admin;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Attribute\Route;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Security\Http\Attribute\IsGranted;
use App\Entity\Book;
use App\Form\BookType;


#[Route('/admin/book')]
class BookController extends AbstractController
{
    #[Route('', name: 'app_admin_book')]
    public function index(): Response
    {
        return $this->render('admin/book/index.html.twig', [
            'controller_name' => 'BookController',
        ]);
    }

    #[Route('/new', name: 'app_admin_book_new', methods: ['GET', 'POST'])]
    #[Route('/{id}/edit', name: 'app_admin_book_edit', requirements: ['id' => '\d+'], methods: ['GET', 'POST'])]
    public function new(?Book $book, Request $request, EntityManagerInterface $manager): Response
    {
        if($book){
            $this->denyAccessUnlessGranted('book.is_creator', $book);
            $this->denyAccessUnlessGranted('ROLE_EDITION_DE_LIVRE');
        }
        else{
            $this->denyAccessUnlessGranted('ROLE_AJOUT_DE_LIVRE');
        }

        $book ??= new Book();
        $form = $this->createForm(BookType::class, $book);
        
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $user = $this->getUser();
            if (!$book->getId() && $user instanceof User){
                $book->setCreatedBy($user);
            }
            $manager->persist($book);
            $manager->flush();

            return $this->redirectToRoute('app_book_index', ['id' => $book->getId()]);
        }

        return $this->render('admin/book/new.html.twig', [
            'form' => $form,
        ]);
    }
}

src/Controller/BookController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Attribute\Route;
use Doctrine\ORM\EntityManagerInterface;
use App\Repository\BookRepository;
use Pagerfanta\Doctrine\ORM\QueryAdapter;
use Pagerfanta\Pagerfanta;
use App\Entity\Book;

#[Route('/book')]
class BookController extends AbstractController
{
    #[Route('', name: 'app_book_index')]
    public function index(Request $request, BookRepository $repository): Response
    {
        $books = Pagerfanta::createForCurrentPageWithMaxPerPage(new QueryAdapter($repository->createQueryBuilder('b')),
        $request->query->get(key: 'page', default : 1), maxPerPage: 4);    

        //$books = $repository->findAll();
        return $this->render('book/index.html.twig', [
            'controller_name' => 'BookController',
            'books' => $books,
        ]);
    }

    #[Route('/{id}', name: 'app_book_show', requirements: ['id' => '\d+'], methods: ['GET'])]
    public function show(?Book $book): Response
    {
        return $this->render('book/show.html.twig', [
            'book' => $book,
        ]);
    }

}

templates/book/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Catalogue des livres{% endblock %}

{% block body %}
    <section class="py-5">
        <div class="container px-4 px-lg-5 mt-5">
            <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                {% for book in books %}
                <div class="col mb-5">
                    <div class="card h-100">
                        <!-- Product image-->
                        <img class="card-img-top" src="{{ book.cover }}" alt="..." />
                        <!-- Product details-->
                        <div class="card-body p-4">
                            <div class="text-center">
                                <!-- Product name-->
                                <h5 class="fw-bolder">{{ book.Title }}</h5>
                                <!-- Product price-->
                                {% for author in book.authors %}
                                {{ author.name }}
                                {% endfor %}
                            </div>
                        </div>
                        <!-- Product actions-->
                        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                            <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{{ path('app_book_show', {id: book.id}) }}">Voir</a></div>
                        </div>
                    </div>
                </div>
                {% else %}
                    <li>Aucun enregistrement en base de donnée</li>
                {% endfor %}
            </div>
                        {{ pagerfanta(books, {'attr': {'class': 'd-flex'}}) }}
        </div>
    </section>
{% endblock %}

templates/book/show.html.twig
{% extends 'base.html.twig' %}

{% set page_title = book is null ? 'Livre inconnu' : book.title %}

{% block title %}{{ page_title}}{% endblock %}

{% block body %}
    <section class="py-5">
        <div class="container px-4 px-lg-5 my-5">
            <div class="row gx-4 gx-lg-5 align-items-center">
                <div class="col-md-6"><img class="card-img-top mb-5 mb-md-0" src="{{ book.cover }}" alt="..." /></div>
                <div class="col-md-6">
                    <div class="small mb-1">ISBN : {{ book.ISBN }}</div>
                    <h1 class="display-5 fw-bolder">{{ book.Title }}</h1>
                    <div class="fs-5 mb-5">
                        <div>Auteur(s) : {{ book.authors|map(a => a.name)|join(', ') }}
                        </div>
                        <div>Editeur : {{ book.editor.name }}</div>
                        <div>{{ book.PageNumber }} pages - {{ book.EditedAt|date('d M Y')}}</div>
                        <div>Statut : {{ book.Status.getLabel() }}</div>
                    </div>
                    <p class="lead">{{ book.Plot }}</p>
                    <div class="d-flex">
                        <a href="{{ path('app_book_index') }}">
                            <button class="btn btn-outline-dark flex-shrink-0" type="button">
                                Retour à la liste
                            </button>
                        </a>
                        <a href="{{ path('app_admin_book_edit', {id: book.id}) }}">
                            <button class="btn flex-shrink-0" type="button">
                                Retour à la liste
                            </button>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}